export const recentMovies = [
  {
    vote_count: 5,
    id: 487283,
    video: false,
    vote_average: 10,
    title: 'A Wish for Giants',
    popularity: 5.036218,
    poster_path: '/pHvnOqNBrPKGzP8orbm9bRpsecK.jpg',
    original_language: 'en',
    original_title: 'A Wish for Giants',
    genre_ids: [12, 18, 14, 878],
    backdrop_path: null,
    adult: false,
    overview:
      'Sophie, a young volunteer, meets her kindred spirit in Roxie, a girl with a life threatening medical condition and a unique wish to meet Bigfoot.',
    release_date: '2018-02-17'
  },
  {
    vote_count: 3,
    id: 369523,
    video: false,
    vote_average: 10,
    title: 'The Tale',
    popularity: 4.407539,
    poster_path: '/liun4hl7vKhfpLi7jwlHunYzuEb.jpg',
    original_language: 'en',
    original_title: 'The Tale',
    genre_ids: [18],
    backdrop_path: '/kLIn55qJLJFGW7qBMlX2vBHJhH3.jpg',
    adult: false,
    overview:
      'An investigation into one woman’s memory as she‘s forced to re-examine her first sexual relationship and the stories we tell ourselves in order to survive.',
    release_date: '2018-01-20'
  },
  {
    vote_count: 2,
    id: 501597,
    video: false,
    vote_average: 10,
    title: 'Gefangen: Der Fall K.',
    popularity: 2.904805,
    poster_path: null,
    original_language: 'de',
    original_title: 'Gefangen: Der Fall K.',
    genre_ids: [18],
    backdrop_path: '/yKidwP3fWO9Pi4oBs5iaMLRXj5G.jpg',
    adult: false,
    overview:
      'For a long time, wealth adviser Elke and car mechanic Wastl were happy together. Until Elke gets involved more and more in dubious financial transactions that bring her success down the line. When her husband wants to stop these windy business, she separates from him. And goes even further - the accusation that her husband has beaten her, brings Wastl for a long time in a psychiatric hospital.',
    release_date: '2018-02-23'
  },
  {
    vote_count: 2,
    id: 489927,
    video: false,
    vote_average: 10,
    title: 'The Kindergarten Teacher',
    popularity: 2.450232,
    poster_path: '/9eRLlwgKsUnN54i33yLz7e9I2g5.jpg',
    original_language: 'en',
    original_title: 'The Kindergarten Teacher',
    genre_ids: [18],
    backdrop_path: '/dayPr7r4A8UhjtT7GzMXkUYTRb2.jpg',
    adult: false,
    overview:
      'Lisa Spinelli is a Staten Island teacher who is unusually devoted to her students. When she discovers one of her five-year-olds is a prodigy, she becomes fascinated with the boy, ultimately risking her family and freedom to nurture his talent.',
    release_date: '2018-01-18'
  },
  {
    vote_count: 2,
    id: 486072,
    video: false,
    vote_average: 10,
    title: 'Leo Da Vinci: Mission Mona Lisa',
    popularity: 2.493132,
    poster_path: '/lFLTGzO05BdYu8AnIeioOHbnyF7.jpg',
    original_language: 'en',
    original_title: 'Leo Da Vinci: Mission Mona Lisa',
    genre_ids: [],
    backdrop_path: '/6lXIPcZfqjemwQ0Mf2TZrq4Jjnr.jpg',
    adult: false,
    overview:
      'Life flows peacefully in Vinci: Leonardo is struggling with his incredible inventions, Lorenzo helps him and Gioconda observes them mockingly. When A mysterious storyteller comes to town and speaks of a hidden treasure, an adventure begins.',
    release_date: '2018-01-11'
  },
  {
    vote_count: 2,
    id: 448491,
    video: false,
    vote_average: 10,
    title: 'Little Forest',
    popularity: 3.994718,
    poster_path: '/wdLmqaJmikJbQgeOK60dtTjqPoz.jpg',
    original_language: 'ko',
    original_title: '리틀 포레스트',
    genre_ids: [18],
    backdrop_path: '/vHlyuIF4wF7xIy5Z2uy60kORn9k.jpg',
    adult: false,
    overview:
      'A young woman leaves the city to return to her hometown in the countryside. Seeking to escape the hustle and bustle of the city, she becomes self-sufficient in a bid to reconnect with nature.',
    release_date: '2018-02-28'
  },
  {
    vote_count: 1,
    id: 345935,
    video: false,
    vote_average: 10,
    title: 'Half Magic',
    popularity: 8.742045,
    poster_path: '/nPJtgVxTqFteUR6aeKktjjSZCS5.jpg',
    original_language: 'en',
    original_title: 'Half Magic',
    genre_ids: [10749, 35],
    backdrop_path: '/ed9kn2sJo0XUgrPKdJGmOV4ceXX.jpg',
    adult: false,
    overview:
      'Three women use their newly formed sisterhood to fight against sexism, bad relationships and low self-esteem. Through embracing their wild adventures, they learn the secret to ultimate fulfillment.',
    release_date: '2018-02-23'
  },
  {
    vote_count: 1,
    id: 438312,
    video: false,
    vote_average: 10,
    title: 'Silariang: Cinta Yang (Tak) Direstui',
    popularity: 2.179023,
    poster_path: '/4O1jjrtR0hZv9gO4lX84N1mfAqF.jpg',
    original_language: 'id',
    original_title: 'Silariang: Cinta Yang (Tak) Direstui',
    genre_ids: [18, 10749],
    backdrop_path: null,
    adult: false,
    overview:
      'Yusuf, a young Makassar man that in love with Zulaikha want to get married. But both of their parents never give them blessed. With love, they run away from their life and get a new life in Rammang Rammang, a small village in Makassar. They live with too much threat. How they will survive from too much pressure in the name of love?',
    release_date: '2018-01-18'
  },
  {
    vote_count: 1,
    id: 459952,
    video: false,
    vote_average: 10,
    title: 'Captain',
    popularity: 2.155274,
    poster_path: '/sJPvD63nFcPktfomGdjvqsmjSU8.jpg',
    original_language: 'ml',
    original_title: 'ക്യാപ്റ്റൻ',
    genre_ids: [18],
    backdrop_path: '/f02hU5fqErE4x4iMw7zsgIzx9w3.jpg',
    adult: false,
    overview:
      'V P Sathyan was a legendary footballer who played for the national team. But lack of recognition and depression forced him to take his own life. Captain is a biopic on the life of V P Sathyan.',
    release_date: '2018-02-16'
  },
  {
    vote_count: 1,
    id: 474116,
    video: false,
    vote_average: 10,
    title: 'Shaitan Ka Bachcha',
    popularity: 1.612748,
    poster_path: null,
    original_language: 'ta',
    original_title: 'Shaitan Ka Bachcha',
    genre_ids: [28, 35],
    backdrop_path: null,
    adult: false,
    overview:
      'Shaitan Ka Bachcha  is an upcoming Indian Tamil action comedy film written and directed by Karthik G. Krish.',
    release_date: '2018-05-25'
  },
  {
    vote_count: 1,
    id: 475954,
    video: false,
    vote_average: 10,
    title: 'The Lion Sleeps Tonight',
    popularity: 1.592004,
    poster_path: '/qAz2WMX05gnXYu01glkNvefu2iA.jpg',
    original_language: 'fr',
    original_title: 'Le lion est mort ce soir',
    genre_ids: [18],
    backdrop_path: '/zHtDhITUXLnDatv6WN1qCuTH42o.jpg',
    adult: false,
    overview:
      'South of France. Present day. Jean, an actor caught up in the past, learns that his current film shoot is unexpectedly suspended for an indefinite period. He takes this opportunity to visit an old friend and settles, clandestinely, into an abandoned house where it happened that Juliette, the great love of his life, once lived. A group of young friends, novice filmmakers, stumble upon the same house and decide it’s the perfect location for their next home-made horror movie. Jean and the kids will meet face to face, sooner or later.',
    release_date: '2018-01-03'
  }
];
